resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc2021.git

jobs:
  - name: build
    public: true
    plan:
      - get: repo
        trigger: true
      - task: check-and-compile
        file: repo/ci/tasks/check-and-compile.yml
      - task: run-solutions
        file: repo/ci/tasks/run-solutions.yml
      - task: run-benchmarks
        file: repo/ci/tasks/run-benchmarks.yml
